####################################################################################################
# Config for Notebook Mailer
####################################################################################################

email_on_success: "support@dmclub.net"
email_on_failure: "support@dmclub.net"

cors_allowed_origin: "http://notes.dmclub.net"
